=== Ju4nr94/LDM-1DAW/UD5/A5.3/Biblioteca_DTD/biblioteca.dtd
<!ELEMENT biblioteca (libros+, usuarios+, prestamos+)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT libros (libro+)>
<!ELEMENT libro (id, nombre, autores, año, editorial, categoria)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (#PCDATA)>

<!ELEMENT usuarios (usuario+)>
<!ELEMENT usuario (id, nombre, apellido+, email+, tipo)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>

<!ELEMENT prestamos (prestamo+)>
<!ELEMENT prestamo (id_usuario, fecha_inicio, fecha_fin, id_libros)>
<!ELEMENT id_usuario (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>
<!ELEMENT id_libros (id+)>

=== Ju4nr94/LDM-1DAW/UD6/A6.1/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./biblioteca.xsl"?>
<!DOCTYPE biblioteca PUBLIC "public-id" "./biblioteca.dtd">
<biblioteca>
    <libros>
        <libro>
            <id>001</id>
            <nombre>Manuel en Sarajevo</nombre>
            <autores>
                <autor>Nicolás García Rodríguez</autor>
                <autor>Álvaro Jaime Moro</autor>
            </autores>
            <año>2025</año>
            <editorial>Vicent Vives</editorial>
            <categoria>Bélico</categoria>
        </libro>
    </libros>
    <usuarios>
        <usuario>
            <id>98765123A</id>
            <nombre>Pepe</nombre>
            <apellido>Pérez</apellido>
            <apellido>Porras</apellido>
            <email>pperpor123@g.educaand.es</email>
            <email>pepeporro@gmail.com</email>
            <tipo>estudiante</tipo>
        </usuario>
    </usuarios>
    <prestamos>
        <prestamo>
            <id_usuario>98765123A</id_usuario>
            <fecha_inicio>15/12/2026</fecha_inicio>
            <fecha_fin>15/01/2027</fecha_fin>
            <id_libros>
                <id>001</id>
            </id_libros>
        </prestamo>
    </prestamos>
</biblioteca>
