=== Ju4nr94/LDM-1DAW/UD5/A5.1/catalogo.dtd
<!ELEMENT catalogo (pelicula+)>

<!ELEMENT pelicula (titulo, director, anio, genero, duracion, actores?)>
<!ATTLIST pelicula id ID #REQUIRED>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>

<!ELEMENT actores (actor+)>
<!ELEMENT actor (#PCDATA)>

=== Ju4nr94/LDM-1DAW/UD5/A5.1/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalogo SYSTEM "catalogo.dtd">
<catalogo>
    <pelicula id="P01">
        <titulo>El Resplandor</titulo>
        <director>Stanley Kubrick</director>
        <anio>1980</anio>
        <genero>Terror</genero>
        <duracion>146 minutos</duracion>
        <actores>
            <actor>Jack Nicholson</actor>
            <actor>Shelley Duvall</actor>
            <actor>Danny Lloyd</actor>
            <actor>Scatman Crothers</actor>
        </actores>
    </pelicula>
    <pelicula id="P02">
        <titulo>Origen</titulo>
        <director>Christopher Nolan</director>
        <anio>2010</anio>
        <genero>Ciencia ficción</genero>
        <duracion>148 minutos</duracion>
    </pelicula>
    <pelicula id="P03">
        <titulo>El Rey León</titulo>
        <director>Rob Minkoff</director>
        <anio>1994</anio>
        <genero>Animación</genero>
        <duracion>88 minutos</duracion>
    </pelicula>
</catalogo>
